{% set name = "hla-polysolver" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_rev: update-polysolver
  git_url: https://github.com/adefelicibus/hla-polysolver.git

build:
  number: 21

requirements:
  host:                                                   
    - perl
    - perl-math-basecalc
    - perl-array-utils
    - perl-vcftools-vcf
    - perl-data-dumper
    - perl-bio-samtools
    - perl-bioperl
    - perl-parallel-forkmanager
    - perl-list-moreutils
    - perl-list-util
    - perl-posix               
    - gcc_linux-64
    - novoalign 3.09*
    - zlib 
    # - libgcc
  build:
    - perl
    - perl-app-cpanminus
    - novoalign 3.09*
    - gcc_linux-64
    - make
    - zlib
  run:
    - strelka
    - gcc_linux-64
    # - libgcc
    - zlib
    - make
    - python 2.7.*
    - perl
    - samtools <=0.1.18
    - novoalign 3.09*
    - java-jdk 7.*
    - perl-posix
    - perl-bioperl
    - perl-list-util
    - perl-list-moreutils
    - perl-parallel-forkmanager
    - perl-data-dumper
    - perl-array-utils
    - perl-vcftools-vcf
    - perl-math-basecalc
    - perl-bio-samtools

# test:
#   source_files:
#     - test/test.bam
#     - test/test.bam.bai
#     - test/test.tumor.bam
#     - test/test.tumor.bam.bai
#     - test/orig.winners.hla.txt
#     - test/orig.indiv.mutect.filtered.nonsyn.annotated
#     - test/orig.call_stats.hla_b_39_01_01_02l.out

about:
  home: https://github.com/adefelicibus/hla-polysolver
  license: BSD
  license_file: LICENSE
  summary: A flow of sequencing data analysis pipeline to type all of the HLA genes in IMGT/HLA database using capture sequenced data or WGS data with high accuracy.
  doc_url: http://archive.broadinstitute.org/cancer/cga/polysolver
  dev_url: 

extra:
  recipe-maintainers:
    - adefelicibus